FROM node:22.3.1

# Set working directory
WORKDIR /var/www/html

# Copy source code
COPY . .

# Install dependencies
RUN npm install

# Expose port Vite
EXPOSE 5173

# Run Vite dev server
CMD ["npm", "run", "dev"]
