version: "3.8"
services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8080:80
      - 443:443

  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: PGSQL_USERNAME
      POSTGRES_PASSWORD: PGSQL_PASSWORD
      POSTGRES_DB: PGSQL_DATABASE
    ports:
      - 9906:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
