version: "3"
services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    volumes:
      - ./www:/var/www/html/
    networks:
      - jatra-net

  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jatra
      POSTGRES_PASSWORD: Jatra@2025
      POSTGRES_DB: db_produksi
    ports:
      - 9906:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - jatra-net

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database
    command: php -S 0.0.0.0:8080 -t /var/www/html
    networks:
      - jatra-net

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/html:/var/www/html
    depends_on:
      - webserver
      - adminer
    networks:
      - jatra-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/html:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html \
             -d adminjatra.jagaamansejahtera.id \
             -d produksi.jagaamansejahtera.id \
             -d dev.produksi.jagaamansejahtera.id \
             --agree-tos --email ali@jatra.co --no-eff-email

networks:
  jatra-net:
    driver: bridge


volumes:
  certbot-etc:
  certbot-var:



