version: "3"
services:
  webserver_prod:
      container_name: webserver_prod
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./www/app-produksi/production:/var/www/html/
      networks:
        - jatra-net

  webserver_dev:
      container_name: webserver_dev
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./www/app-produksi/development:/var/www/html/
      networks:
        - jatra-net

  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: jatra
      POSTGRES_PASSWORD: Jatra@2025
      POSTGRES_DB: db_produksi
    command: ["postgres", "-c", "max_locks_per_transaction=256"]
    ports:
      - 9906:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - jatra-net

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
  #   depends_on:
  #     - database
  #   command: php -S 0.0.0.0:8080 -t /var/www/html
  #   networks:
  #     - jatra-net

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - webserver_prod
      - webserver_dev
      # - adminer
    networks:
      - jatra-net

networks:
  jatra-net:
    driver: bridge



